name: Continues Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  clippy:
    name: Clippy check (${{ matrix.target }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            args: ""
          - target: wasm32-unknown-unknown
            args: "--target wasm32-unknown-unknown"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo clippy-all ${{ matrix.args }}

  check-build:
    name: Check build (${{ matrix.target }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            args: ""
          - target: wasm32-unknown-unknown
            args: "--target wasm32-unknown-unknown"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo check ${{ matrix.args }}

  test:
    name: Integration test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo test-core
          cargo test-interface
          cargo test-jarust
          cargo test-plugins

  e2e:
    name: E2E tests
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: hoverkraft-tech/compose-action@v2.0.1
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test-e2e
