name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.2.3)"
        required: true
        type: string

# For creating gh releases
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MACHINE_USER_TOKEN }}
          fetch-depth: 0

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Validate version
        run: ./scripts/validate_version.sh "${{ github.event.inputs.version }}"

      - name: Update Cargo.toml versions
        run: ./scripts/update_versions.sh "${{ github.event.inputs.version }}"

      - name: Build release
        run: cargo build --release

      - name: Create git tag and push
        run: ./scripts/release_tag.sh "${{ github.event.inputs.version }}" "${{ secrets.MACHINE_USER_EMAIL }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Publish to crates.io
        if: env.CRATES_TOKEN != ''
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: ./scripts/publish_crates.sh "$CRATES_TOKEN"
